services:
  - type: web
    name: django-auth-app
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false